api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    eager_loading:
        enabled: true
    collection:
        pagination:
            enabled: true
            page_parameter_name: _page
            client_enabled: true
            enabled_parameter_name: pagination
            items_per_page: 5
            client_items_per_page: true
            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 100
    exception_to_status:
        App\Exception\EmptyBodyException: 400
